# Generated by Django 4.2.5 on 2023-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('date_found', models.DateField(null=True)),
                ('date_lost', models.DateField(null=True)),
                ('location_found', models.CharField(max_length=100)),
                ('location_lost', models.CharField(max_length=100)),
                ('isFound', models.BooleanField(default=False)),
                ('name_of_item_owner', models.CharField(max_length=100)),
                ('name_of_item_finder', models.CharField(max_length=100)),
                ('phone_number_of_item_owner', models.CharField(max_length=100)),
                ('phone_number_of_item_finder', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
